version: "3.2"

services:
    website_portal:
        network_mode: host
        image: nginx
        container_name: website_portal

        # reload config + certs every 6h
        # needed if certs are renewed in this time
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

        ports:
        - 80:80
        - 443:443

        volumes:
        - type: bind
          source: ./portal/nginx/nginx.conf
          target: /etc/nginx/conf.d/default.conf

        - type: bind
          source: ./portal/nginx/htpasswd
          target: /etc/nginx/conf.d/htpasswd

        - type: bind
          source: ./portal/data/certbot/conf
          target: /etc/letsencrypt

        - type: bind
          source: ./portal/data/certbot/www
          target: /var/www/certbot

        depends_on:
        - blog


    certbot:
        image: certbot/certbot
        container_name: website_certbot

        # automatic cert renewal
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

        volumes:
        - type: bind
          source: ./portal/data/certbot/conf
          target: /etc/letsencrypt

        - type: bind
          source: ./portal/data/certbot/www
          target: /var/www/certbot


    blog:
        image: nginx
        container_name: blog_files

        ports:
        - 8081:80

        volumes:
        - type: bind
          source: ./blog/public
          target: /usr/share/nginx/html

        - type: bind
          source: ./blog/blog-nginx.conf
          target: /etc/nginx/conf.d/default.conf
